spring:
  datasource:
    username: root
    password: yangweibin123
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合别名(mybatis)
mybatis.type-aliases-package: com.example.demo.pojo
mybatis.mapper-locations: classpath:mybatis/mapper/*.xml
